// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace DynamicFormsCore
{
    public partial class DbformsContext : DbContext
    {
        public DbformsContext()
        {
        }

        public DbformsContext(DbContextOptions<DbformsContext> options)
            : base(options)
        {
        }

        public virtual DbSet<DataForm> DataForm { get; set; }
        public virtual DbSet<DataFormField> DataFormField { get; set; }
        public virtual DbSet<DataFormFieldType> DataFormFieldType { get; set; }
        public virtual DbSet<DataFormSection> DataFormSection { get; set; }
        public virtual DbSet<DataFormSubmission> DataFormSubmission { get; set; }
        public virtual DbSet<DataFormSubmissionItem> DataFormSubmissionItem { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<DataFormSubmissionItem>().HasKey(c => new { c.DataFormFieldId, c.DataFormSubmissionId });
            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}