// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DynamicFormsCore
{
    [Table("DataFormSection")]
    public partial class DataFormSection
    {
        //public DataFormSection()
        //{
        //    DataFormField = new HashSet<DataFormField>();
        //}

        [Key]
        public Guid Id { get; set; }

        [Required]
        [StringLength(150)]
        public string SectionName { get; set; }

        public Guid DataFormId { get; set; }

        //[ForeignKey(nameof(DataFormId))]
        //[InverseProperty("DataFormSection")]
        //public virtual DataForm DataForm { get; set; }

        //[InverseProperty("DataFormSection")]
        public virtual IList<DataFormField> DataFormField { get; set; }
    }
}