// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DynamicFormsCore
{
    [Table("DataFormSubmissionItem")]
    public partial class DataFormSubmissionItem
    {
        //[Key, Column(Order = 0)]
        public Guid DataFormFieldId { get; set; }

        //[Key, Column(Order = 1)]
        public Guid DataFormSubmissionId { get; set; }

        public int? FieldIntValue { get; set; }

        [StringLength(150)]
        public string FieldStringValue { get; set; }

        [Column(TypeName = "datetime")]
        public DateTime? FieldDateValue { get; set; }

        public double? FieldFloatValue { get; set; }

        [Column(TypeName = "ntext")]
        public string FieldTextValue { get; set; }

        public byte[] FieldBinaryValue { get; set; }

        public Guid? FieldGuidValue { get; set; }

        public bool? FieldBoolValue { get; set; }

        //[ForeignKey(nameof(DataFormFieldId))]
        //[InverseProperty("DataFormSubmissionItem")]
        public virtual DataFormField DataFormField { get; set; }

        //[ForeignKey(nameof(DataFormSubmissionId))]
        //[InverseProperty("DataFormSubmissionItem")]
        //public virtual DataFormSubmission DataFormSubmission { get; set; }
    }
}