// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DynamicFormsCore
{
    [Table("DataForm")]
    public partial class DataForm
    {
        //public DataForm()
        //{
        //    DataFormSection = new HashSet<DataFormSection>();
        //    //DataFormSubmission = new HashSet<DataFormSubmission>();
        //}

        [Key]
        public Guid Id { get; set; }

        [Required]
        [StringLength(150)]
        public string FormName { get; set; }

        //[InverseProperty("DataForm")]
        public virtual IList<DataFormSection> DataFormSection { get; set; }

        //[InverseProperty("DataForm")]
        //public virtual ICollection<DataFormSubmission> DataFormSubmission { get; set; }
    }
}