// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DynamicFormsCore
{
    [Table("DataFormSubmission")]
    public partial class DataFormSubmission
    {
        //public DataFormSubmission()
        //{
        //    DataFormSubmissionItem = new HashSet<DataFormSubmissionItem>();
        //}

        [Key]
        public Guid Id { get; set; }

        public Guid DataFormId { get; set; }

        [Column(TypeName = "datetime")]
        public DateTime? SubmitDateUTC { get; set; }

        [Column(TypeName = "datetime")]
        public DateTime? SubmitDateLocal { get; set; }

        //[ForeignKey(nameof(DataFormId))]
        //[InverseProperty("DataFormSubmission")]
        //public virtual DataForm DataForm { get; set; }

        //[InverseProperty("DataFormSubmission")]
        public virtual IList<DataFormSubmissionItem> DataFormSubmissionItem { get; set; }
    }
}